### ISSUE TITLE
Set behavior not like in preview

### ISSUE THREAD

**Issue by Monabr** [skydoves/colorpicker-compose#10]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Color sets only after new click

**Expected Behavior:**

Color sets also while drag

-------------------
I found out that drag just doesn't work.

----Update 1----
I found out that drag not working if scroll enabled.

----Update 2----
this repo does not have this problem https://github.com/SmartToolFactory/Jetpack-Compose-Tutorials#gesture

**Comment by skydoves** [comment]
I'm not sure, but could you check if you adjust the nested scrolling behaviors with this modifier? https://developer.android.com/reference/kotlin/androidx/compose/ui/input/nestedscroll/package-summary#(androidx.compose.ui.Modifier).nestedScroll(androidx.compose.ui.input.nestedscroll.NestedScrollConnection,androidx.compose.ui.input.nestedscroll.NestedScrollDispatcher)
