### ISSUE TITLE
Set wheel alpha only applies to picker not sliders

### ISSUE THREAD

**Issue by coderforlife** [skydoves/colorpicker-compose#16]
**Please complete the following information:**
- Library Version: v1.0.1
 
**Describe the Bug:**
Set wheel alpha only applies to picker not sliders. The little white dot is still pure white on the others. This probably applies to all of the "wheel" settings. I would expect them to all be consistent.

**Comment by skydoves** [comment]
This issue was fixed in the new release, 1.0.2. Thanks for reporting this issue!
