### ISSUE TITLE
Wrong border size is applied

### ISSUE THREAD

**Issue by petin** [skydoves/colorpicker-compose#17]
- Library Version v1.0.1
- Affected Device(s) - all
 

**Bug description:**

When setting the `borderSize` for the `BrightnessSlider` the value is defined in `DP`. However the library does not converts it into `pixels`, but just takes the DP value:
```
strokeWidth = borderSize.value
```

This causes that `5.dp` border is applied as `5.px`.

Same issue is with the `borderSize` when it is applied with `.drawRoundRect`

**Expected Behavior:**

The DP should be properly calculated to pixels (according to the current density), so the correct size is applied

**Comment by skydoves** [comment]
This issue was fixed in the new release, 1.0.2. Thanks for reporting this issue!
