### ISSUE TITLE
Can't drag to select colour with HsvColorPicker

### ISSUE THREAD

**Issue by user154lt** [skydoves/colorpicker-compose#25]
- Library Version [1.0.2]
- Affected Device(s) [Oppo Find x3 Pro A13]
 
**Describe the Bug:**
Can only click to set colour with the HsvColorPicker unless there are multiple touches on the screen.
Sorry if that does not make much sense, what I mean is that if I have two or more fingers on the screen I can drag the selector as expected but if I Just have one finger on the selector I cannot drag it.

Below is my code to instantiate the colour picker:

@Composable
fun ColorWheelPicker(modifier: Modifier = Modifier) {
    val controller = rememberColorPickerController()
    HsvColorPicker(
        modifier = modifier
            .height(450.dp)
            .padding(16.dp),
        controller = controller
    )
}

**Expected Behavior:**

I am not sure if this the intended behaviour but my expectation was that I would be able to drag the selector with one finger

**Comment by skydoves** [comment]
This issue has been fixed and it's available in the new version 1.0.3. Thanks for reporting this issue!

**Comment by user154lt** [comment]
Thanks so much for fixing this, I really wanted to use this in my app but ending up going in a different direction. I can't wait to try it out! Thanks so much again!
