### ISSUE TITLE
Debounce does not work with the brightness slider

### ISSUE THREAD

**Issue by turaib** [skydoves/colorpicker-compose#26]
- Library Version 1.0.2
- Affected Device: Samsung Galaxy s22 with Android 11.0
 
**Describe the Bug:**

Add a clear description about the problem.
If I set the debounce time on the controller, it has no effect on the brightness slider.

**Expected Behavior:**
Like the HSV colorpicker, the onColorChanged callback should only be called with a regularity corresponding to the debounce time.

**Comment by skydoves** [comment]
This issue has been fixed and it's available in the new version 1.0.3. Thanks for reporting this issue!
