### ISSUE TITLE
Could not resolve all dependencies for configuration

### ISSUE THREAD

**Issue by 7FULL** [skydoves/colorpicker-compose#44]
**Please complete the following information:**
- Library Version [v1.0.5]
- Affected Device(s) [Pixel 7 Pro]
 
**Describe the Bug:**
Added the dependencia in the build gradle and it throws this

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Problems reading data from Binary store in C:\Users\phgfu\.gradle\.tmp\gradle9238719398653078878.bin offset 68796 exists? true
Corrupt serialized resolution result. Cannot find selected module (602) for releaseRuntimeElements-published -> androidx.compose.material3:material3-window-size-class

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Problems reading data from Binary store in C:\Users\phgfu\.gradle\.tmp\gradle9238719398653078878.bin offset 68796 exists? true
Corrupt serialized resolution result. Cannot find selected module (602) for releaseRuntimeElements-published -> androidx.compose.material3:material3-window-size-class
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:412)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:138)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:64)
	at ...

Add a clear description about the problem.
Jus added the dependencia and clicked Sync now and it throws that

Sorry Im new to android so maybe it can be a stupidity.

Sorry for my english btw. Regards from Spain

**Comment by skydoves** [comment]
This issue seems to come from the Gradle caching problem. You can mostly resolve this issue by cleaning and rebuilding the project.
