### ISSUE TITLE
Color code input field

### ISSUE THREAD

**Issue by JohnSobhy** [skydoves/colorpicker-compose#50]
Great library, very useful and easy to use! 
I want to recommend adding a field where the user can enter a color code whether the hex or argb value, the field would be connected to the controller of course, and the color then be applied to both the hsv wheel and the alpha tile.  if this can already be achieved by the current version, I would really appreciate an example of how to do it. Thank you.

**Comment by skydoves** [comment]
Hey @JohnSobhy, I'm sorry for the late response. Now, it's available the new method below from the `ColorPickerController`:

```kotlin
selectByHsv(hsv: FloatArray, alpha: Float, fromUser: Boolean)
```

Thank you for raising this issue and for your patience!
