### ISSUE TITLE
HsvColorPicker resets ViewModel UiStatus

### ISSUE THREAD

**Issue by dominikbell** [skydoves/colorpicker-compose#51]
**Please complete the following information:**
- Library Version [e.g. v1.0.7]
- Affected Device(s) [virtual Pixel 7 API 33]
 
**Describe the Bug:**

When using the `HsvColorPicker` to update the attribute of a `ViewModel` it resets the other attributes of it. Here is an example code:
The ViewModel class looks something like this
```
class EditTagViewModel(
    private val appRepository: AppRepository,
    savedStateHandle: SavedStateHandle
): ViewModel() {
    private val boxId: Long = checkNotNull(savedStateHandle["boxId"])
    var tagUiState by mutableStateOf(TagState())

    fun updateUiState(tagDetails: TagDetails) {
        tagUiState = TagState(
            tagDetails = tagDetails
        )
    }
}
```
where `TagState` has the property `TagDetails` which holds the `text` and `color`.

The composable looks like this
```
OutlinedTextField(
    value = tagUiState.tagDetails.text,
    label = { Text(text = "Tag Name") },
    onValueChange = {
        editTagViewModel.updateUiState(
            tagUiState.tagDetails.copy(text = it)
        )
    }
)

HsvColorPicker(
    modifier = Modifier
        .fillMaxWidth()
        .height(200.dp),
    controller = controller,
    onColorChanged = { colorEnvelope: ColorEnvelope ->
        editTagViewModel.updateUiState(
            tagUiState.tagDetails.copy(color = colorEnvelope.hexCode)
    }
)
```

First setting the color and then the text works as expected.

**Expected Behavior:**

A color change on the `HsvColorPicker` only changes the color attribute, and does not reset the text. I am not an expert but this might be a problem of scope.

**Comment by skydoves** [comment]
This issue is not related to this library. Instead, it's very related to the recomposition scope. I'd like to provide a great article for this:

https://www.jetpackcompose.app/articles/donut-hole-skipping-in-jetpack-compose
